---
kind: pkgfile.Build
spec:
  targets:
    - sbc-rockchip
  extraBuildArgs:
    - PKGS_PREFIX
    - PKGS
  makefile:
    extraVariables:
      - name: PKGS_PREFIX
        defaultValue: ghcr.io/siderolabs
      - name: PKGS
        defaultValue: v1.9.0-1-gb047e41
      - name: PKG_KERNEL
        defaultValue: ghcr.io/siderolabs/kernel:v1.9.0-1-gb047e41
---
kind: common.Build
spec:
    ignoredPaths:
      - go.work.sum
